//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimOA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActionInfo()
        {
            this.UserActionInfo = new HashSet<UserActionInfo>();
            this.RoleInfo = new HashSet<RoleInfo>();
        }
    
        public long ActionId { get; set; }
        public string ActionTitle { get; set; }
        public string AddTime { get; set; }
        public string Remark { get; set; }
        public byte IsDeleted { get; set; }
        public string ModifiedTime { get; set; }
        public long SubBy { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public byte IsMenu { get; set; }
        public string MenuIcon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActionInfo> UserActionInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
    }
}
