//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimOA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.UserActionInfo = new HashSet<UserActionInfo>();
            this.RoleInfo = new HashSet<RoleInfo>();
        }
    
        public long UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int ErrorCount { get; set; }
        public string ErrorTime { get; set; }
        public byte IsDeleted { get; set; }
        public string RealName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string AddTime { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public string ModifiedTime { get; set; }
        public long SubBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActionInfo> UserActionInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
    }
}
