//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimOA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFModel
    {
        public long ModelId { get; set; }
        public string ModelTitle { get; set; }
        public string AddTime { get; set; }
        public string Remark { get; set; }
        public byte IsDeleted { get; set; }
        public string ModifiedTime { get; set; }
        public long SubBy { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
    }
}
