//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimOA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFStep
    {
        public long StepId { get; set; }
        public long InstanceId { get; set; }
        public string Tips { get; set; }
        public long SubBy { get; set; }
        public string SubTime { get; set; }
        public string Remark { get; set; }
        public long NextId { get; set; }
        public byte IsEnd { get; set; }
    
        public virtual WFInstance WFInstance { get; set; }
    }
}
